version: '3'

services:

  mysql:
    image: javanile/mysql:8.0.31
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST
      - MYSQL_ROOT_PASSWORD

  backup:
    image: databack/mysql-backup
    environment:
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - SINGLE_DATABASE=true
      - DB_DUMP_BY_SCHEMA=true
      - DB_DUMP_FREQ=10080
      - DB_DUMP_BEGIN=0300
      - DB_DUMP_TARGET=smb://${SMB_HOST}/${SMB_SHARE}${SMB_PATH}
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASSWORD}
